

services:
  web:
    build: .
    
    volumes:
      - .:/app
      
    ports:
      - "8000:8000"
    env_file:
      - .env.web
    environment:
      - DJANGO_DEBUG=False
      - GDAL_DATA=/usr/share/gdal
      - DJANGO_SETTINGS_MODULE=mysite.settings.settings
    
      
      
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput -v 3 &&
             daphne -b 0.0.0.0 -p 8000 mysite.asgi:application"



  

  

  

  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    command: >
      sh -c "
      echo 'Starting Nginx in HTTP mode...'
      nginx -g 'daemon on;'
      while [ ! -f /etc/letsencrypt/live/foodonline.run.place/fullchain.pem ]; do
      echo 'Waiting for SSL certificates...'
      sleep 5
      done
      echo 'Switching to HTTPS configuration'
      nginx -s quit
      nginx -g 'daemon off;'
      "
     
    depends_on:
      - web
    
    
        

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    depends_on:
      - nginx
        
    volumes:
      - certbot-certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
      -d foodonline.run.place -d www.foodonline.run.place
      --email mahasethmanish63@gmail.com --agree-tos --no-eff-email"

volumes:
  certbot-certs:
  certbot-www: