

services:
  web:
    build: .
    
    volumes:
      - .:/app
      
    ports:
      - "8000:8000"
    env_file:
      - .env.web
    environment:
      - DJANGO_DEBUG=False
      - GDAL_DATA=/usr/share/gdal
      - DJANGO_SETTINGS_MODULE=mysite.settings.settings
    healthcheck:
      test: ["CMD","wget","--spider","http://web:8000/"]  
      interval: 5s
      timeout: 3s
      retries: 10
      
      
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput -v 3 &&
             daphne -b 0.0.0.0 -p 8000 mysite.asgi:application"



  

  

  

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: unless-stopped
    depends_on:
      web:
        condition: service_healthy
    # Critical addition: NGINX must serve challenge files
    command: >
      sh -c "echo 'Starting NGINX in temporary mode for certificate issuance';
             nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: >
      sh -c "echo 'Waiting for NGINX to be ready...';
             sleep 15;
             echo 'Requesting certificates...';
             certbot certonly --webroot -w /var/www/certbot 
             --email mahasethmanish63@gmail.com 
             --agree-tos --no-eff-email 
             -d foodonline.run.place 
             -d www.foodonline.run.place 
             --non-interactive; 
             
             if [ -f /etc/letsencrypt/live/foodonline.run.place/fullchain.pem ]; then
               echo 'SUCCESS: Certificates created!';
               exit 0;
             else
               echo 'ERROR: Certificate creation failed';
               exit 1;
             fi"
    restart: on-failure
    depends_on:
      - nginx
