

services:
  web:
    build: .
    
    volumes:
      - .:/app
      
    ports:
      - "8000:8000"
    env_file:
      - .env.web
    environment:
      - DJANGO_DEBUG=False
      - GDAL_DATA=/usr/share/gdal
      - DJANGO_SETTINGS_MODULE=mysite.settings.settings
    healthcheck:
      test: ["CMD","wget","--spider","http://localhost:8000/"]  
      interval: 5s
      timeout: 3s
      retries: 10
      
      
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput -v 3 &&
             daphne -b 0.0.0.0 -p 8000 mysite.asgi:application"



  

  

  

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
     
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    
    restart:  unless-stopped  
    depends_on:
      web:
        condition: service_healthy

  certbot:
    image:  certbot/certbot
    volumes:
     - ./certbot/www:/var/www/certbot   
     - ./certbot/conf:/etc/letsencrypt 

    command: certonly --webroot -w /var/www/certbot --email mahasethmanish63@gmail.com --agree-tos --no-eff-email -d foodonline.run.place -d www.foodonline.run.place --non-interactive --staging
    restart: on-failure
    depends_on:
      - nginx 
    

  