

services:
  web:
    build: .
    
    volumes:
      - .:/app
      
    ports:
      - "8000:8000"
    env_file:
      - .env.web
    environment:
      - DJANGO_DEBUG=False
      - GDAL_DATA=/usr/share/gdal
      - DJANGO_SETTINGS_MODULE=mysite.settings.settings
      
      
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 mysite.asgi:application"



  

  

  

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
     
      - ./certbot/conf:/etc/letsencrypt
      - ./webroot:/var/www/certbot
    depends_on:
      - web
    


  
  