

services:
  web:
    build: .
    
    volumes:
      - .:/app
      
    ports:
      - "8000:8000"
    env_file:
      - .env.web
    environment:
      - DJANGO_DEBUG=False
      - GDAL_DATA=/usr/share/gdal
      - DJANGO_SETTINGS_MODULE=mysite.settings.settings
    
      
      
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput -v 3 &&
             daphne -b 0.0.0.0 -p 8000 mysite.asgi:application"



  

  

  

  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - web
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 10
        

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    depends_on:
      nginx:
        condition: service_healthy
    volumes:
      - certbot-certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    command: >
      sh -c "echo 'Waiting for Nginx to be fully ready...';
      sleep 10;
      certbot certonly --webroot -w /var/www/certbot
      -d foodonline.run.place -d www.foodonline.run.place
      --email mahasethmanish63@gmail.com
      --agree-tos --non-interactive --force-renewal;
      echo 'Certbot setup complete'"

volumes:
  certbot-certs:
  certbot-www: