

services:
  web:
    build: .
    depends_on:
      - inventory_db
      - redis
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_DEBUG=False
      - GDAL_DATA=/usr/share/gdal
      - DJANGO_SETTINGS_MODULE=mysite.settings
      
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 mysite.asgi:application"

  inventory_db:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MANISH@123
      POSTGRES_DB: foodonline2
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis_data:/data
    restart: always

  celery_worker:
    build: .
    command: celery -A mysite worker --loglevel=info --concurrency=2
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_DEBUG=False  # Should be False in production
      - GDAL_DATA=/usr/share/gdal
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - POSTGRES_HOST=inventory_db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=foodonline2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MANISH@123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - inventory_db
    restart: unless-stopped

  celery_beat:
    build: .
    command: celery -A mysite beat --loglevel=info
    volumes:
      - .:/app
      - beat_data:/var/celery
    env_file:
      - .env
    environment:
      - DJANGO_DEBUG=False  # Should be False in production
      - GDAL_DATA=/usr/share/gdal
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - POSTGRES_HOST=inventory_db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=foodonline2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MANISH@123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BEAT_SCHEDULE_FILENAME=/var/celery/beat-schedule
    depends_on:
      - redis
      - inventory_db
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
    

volumes:
  postgres_data:
  redis_data:
  beat_data:
  static_volume:
  media_volume:
  