all:
  children:
    web_servers:
      hosts:
        web01:
          ansible_host:  54.210.71.179
          ansible_user: ubuntu
        web02:
          ansible_host: 13.221.43.214
          ansible_user: ubuntu