all:
  children:
    web_servers:
      hosts:
        web01:
          ansible_host:  100.57.146.169
          ansible_user: ubuntu
        web02:
          ansible_host: 100.55.118.125
          ansible_user: ubuntu