# Generated by Django 5.2 on 2025-05-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_active_user_is_admin_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cover_phoe',
            new_name='cover_photo',
        ),
    ]
