---
- name: Deploy Django app from Jenkins workspace to EC2
  hosts: web_servers
  become: yes
  vars:
    app_dir: "/opt/multivendor"
    env_file_path_for_web01: "/opt/multivendor/.env.prod"
    env_file_path_for_web02: "/opt/multivendor/.env.redis.prod"
    ecr_registry: "822417885273.dkr.ecr.us-east-1.amazonaws.com"
    ecr_repo: "multivendor"
    ecr_image_tag: "{{ ecr_image_tag }}"
    compose_files_for_web01: "docker-compose.prod.yml"
    compose_files_for_web02: "docker-compose-tier.yml"

  tasks:
    - name: Ensure app directory exists
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Copy .env.prod from Jenkins secret to web01
      copy:
        src: "{{ secret_file_path }}"
        dest: "{{ env_file_path_for_web01 }}"
        mode: '0600'
      when: inventory_hostname == "web01"

    - name: Copy .env.redis.prod from Jenkins secret to web02
      copy:
        src: "{{ secret_file_path_redis }}"
        dest: "{{ env_file_path_for_web02 }}"
        mode: '0600'
      when: inventory_hostname == "web02"
    
    - name: Render docker-compose.prod.yml
      template:
        src: docker-compose.prod.yml.j2
        dest: "{{ app_dir }}/docker-compose.prod.yml"

    - name: Render docker-compose-tier.yml
      template:
        src: docker-compose-tier.yml.j2
        dest: "{{ app_dir }}/docker-compose-tier.yml"

    - name: Install awscli 
      apt:
        name: awscli
        state: present
        update_cache: yes

    - name: Log in to Amazon ECR
      shell: |
        aws ecr get-login-password --region us-east-1 | \
        docker login --username AWS --password-stdin {{ ecr_registry }}  
    - name: Remove all the images 
      shell: |
        docker rmi $(docker images -q) || true
    - name: Remove all the containers 
      shell: |
        docker rm $(docker ps -a -q) || true    
    - name: Pull the Docker image from ECR
      docker_image:
        name: "{{ ecr_registry }}/{{ ecr_repo }}:{{ ecr_image_tag }}"
        source: pull
    
    - name: Deploy with Docker Compose on web01
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        files:
          - "{{ compose_files_for_web01 }}"
        state: present
      when: inventory_hostname == "web01"
    - name: Deploy with Docker Compose on web02
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        files:
          - "{{ compose_files_for_web02 }}"
        state: present
      when: inventory_hostname == "web02"                

