# Generated by Django 5.2 on 2025-05-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='esewa', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('accepted', 'accepted'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='new', max_length=25),
        ),
    ]
