# Generated by Django 5.2 on 2025-05-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_payment_method_order_total_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedfood',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('accepted', 'accepted'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='new', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('accepted', 'accepted'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='new', max_length=25),
        ),
    ]
