# Generated by Django 5.2.1 on 2025-05-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderedfood_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedfood',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('accepted', 'accepted'), ('completed', 'completed'), ('cancelled_by_customer', 'cancelled_by_customer'), ('cancelled', 'cancelled')], default='new', max_length=25),
        ),
    ]
