# Generated by Django 5.2.1 on 2025-05-16 23:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('order', '0005_alter_order_total_alter_orderedfood_amount_and_more'),
        ('vendor', '0005_alter_openinghour_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrefund',
            name='order',
        ),
        migrations.RemoveField(
            model_name='customerrefund',
            name='ordered_food',
        ),
        migrations.AlterUniqueTogether(
            name='vendorpayout',
            unique_together={('vendor', 'payout_date')},
        ),
        migrations.AddField(
            model_name='customerrefund',
            name='original_order',
            field=models.JSONField(default={'HLW': 'HLW'}),
        ),
        migrations.AddField(
            model_name='customerrefund',
            name='refunded_items',
            field=models.JSONField(default={'HLW': 'HLW'}),
        ),
        migrations.AddField(
            model_name='customerrefund',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed')], default='pending'),
        ),
        migrations.AddField(
            model_name='orderedfood',
            name='is_payout_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderedfood',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='food_data',
            field=models.JSONField(default={'HLW': 'HLW'}, help_text='food item data at payout time'),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='order_data',
            field=models.JSONField(default={'HLW': 'HLW'}, help_text='structured order data at payout time'),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerrefund',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_refund', to='order.payment'),
        ),
        migrations.AlterField(
            model_name='vendorpayout',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vendorpayout',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_payout', to='order.payment'),
        ),
        migrations.AlterField(
            model_name='vendorpayout',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='vendor.vendor'),
        ),
        migrations.AddIndex(
            model_name='orderedfood',
            index=models.Index(fields=['status', 'updated_at'], name='order_order_status_03226b_idx'),
        ),
        migrations.RemoveField(
            model_name='vendorpayout',
            name='order',
        ),
        migrations.RemoveField(
            model_name='vendorpayout',
            name='ordered_food',
        ),
    ]
