# Generated by Django 5.2.1 on 2025-05-16 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_customerrefund_order_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorpayout',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vendorpayout',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='vendorpayout',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='CustomerRefund',
        ),
        migrations.DeleteModel(
            name='VendorPayout',
        ),
    ]
