# Generated by Django 5.2.1 on 2025-05-19 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_customerrefund_vendorpayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedfood',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderedfood',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('accepted', 'accepted'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('cancelled_in_payment_gateway', 'cancelled_in_payment_gateway')], default='new', max_length=50),
        ),
    ]
