# Generated by Django 5.2.1 on 2025-05-20 01:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('order', '0009_alter_orderedfood_order_alter_orderedfood_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderedfood',
            name='order_order_status_03226b_idx',
        ),
        migrations.AddIndex(
            model_name='orderedfood',
            index=models.Index(fields=['created_at'], name='order_order_created_31ef5c_idx'),
        ),
    ]
