# Generated by Django 5.2.1 on 2025-05-23 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('order', '0010_remove_orderedfood_order_order_status_03226b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrefund',
            name='is_fully_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('complete', 'completd'), ('canceled', 'canceled'), ('pending', 'pending')], max_length=100),
        ),
        migrations.AddIndex(
            model_name='orderedfood',
            index=models.Index(fields=['status'], name='order_order_status_bbbaf8_idx'),
        ),
        migrations.AddIndex(
            model_name='orderedfood',
            index=models.Index(fields=['order', 'status'], name='order_order_order_i_2dc018_idx'),
        ),
    ]
