# Generated by Django 5.2.1 on 2025-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_customerrefund_is_fully_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('complete', 'completed'), ('canceled', 'canceled'), ('pending', 'pending')], max_length=100),
        ),
    ]
