# Generated by Django 5.2.1 on 2025-05-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayout',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
