# Generated by Django 5.2.1 on 2025-05-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_vendorpayout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpayout',
            name='payout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
