# Generated by Django 5.2.1 on 2025-05-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_vendorpayout_payout_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorpayout',
            unique_together=set(),
        ),
    ]
