# Generated by Django 5.2.1 on 2025-05-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_vendorpayout_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpayout',
            name='payout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
